name: Deploy a Hosting por FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Subir archivos al hosting
    runs-on: ubuntu-latest
    environment: "New repository secret"
    steps:
      - name: Obtener repositorio
        uses: actions/checkout@v4

      - name: Sincronizar archivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            .gitignore
            netlify.toml
            media_index.html